STORY1151
appveen/ds-service-manager pull request #49
Opened 2022-11-02 08:08 UTC by kavi-appveen

2022-11-02 09:56 UTC, jerrymannel requested changes
Add the default connector only of the user has not selected a DB connector. Please make that change.

2022-11-07 05:28 UTC, jugnu-appveen approved these changes

2022-11-07 05:40 UTC, jugnu-appveen approved these changes

2022-11-07 09:51 UTC, jerrymannel approved these changes

2022-11-07 09:51 UTC, merged